function SetMovementAnim(pHash)
	local playerPed = PlayerPedId()
	RequestAnimSet(pHash)
	while not HasAnimSetLoaded(pHash) do
		Citizen.Wait(0)
	end
	SetPedMovementClipset(playerPed, pHash, 1.0)
end

RegisterNetEvent('SetCustomMovementStyle:michael')
AddEventHandler('SetCustomMovementStyle:michael', function()
	SetMovementAnim("move_characters@michael@fire")
end)

RegisterNetEvent('SetCustomMovementStyle:jimmy')
AddEventHandler('SetCustomMovementStyle:jimmy', function()
	SetMovementAnim("move_characters@Jimmy@slow@")
end)

RegisterNetEvent('SetCustomMovementStyle:franklin')
AddEventHandler('SetCustomMovementStyle:franklin', function()
	SetMovementAnim("move_characters@franklin@fire")
end)

RegisterNetEvent('SetCustomMovementStyle:lester')
AddEventHandler('SetCustomMovementStyle:lester', function()
	SetMovementAnim("move_heist_lester")
end)

RegisterNetEvent('SetCustomMovementStyle:gangster1')
AddEventHandler('SetCustomMovementStyle:gangster1', function()
	SetMovementAnim("move_m@gangster@var_e")
end)

RegisterNetEvent('SetCustomMovementStyle:gangster2')
AddEventHandler('SetCustomMovementStyle:gangster2', function()
	SetMovementAnim("move_m@gangster@var_f")
end)

RegisterNetEvent('SetCustomMovementStyle:gangster3')
AddEventHandler('SetCustomMovementStyle:gangster3', function()
	SetMovementAnim("move_m@gangster@var_i")
end)

RegisterNetEvent('SetCustomMovementStyle:gangster4')
AddEventHandler('SetCustomMovementStyle:gangster4', function()
	SetMovementAnim("MOVE_M@GANGSTER@NG")
end)

RegisterNetEvent('SetCustomMovementStyle:enerve')
AddEventHandler('SetCustomMovementStyle:enerve', function()
	SetMovementAnim("move_m@fire")
end)

RegisterNetEvent('SetCustomMovementStyle:brave')
AddEventHandler('SetCustomMovementStyle:brave', function()
	SetMovementAnim("move_m@brave")
end)

RegisterNetEvent('SetCustomMovementStyle:classique')
AddEventHandler('SetCustomMovementStyle:classique', function()
	SetMovementAnim("move_m@casual@d")
end)

RegisterNetEvent('SetCustomMovementStyle:determine')
AddEventHandler('SetCustomMovementStyle:determine', function()
	SetMovementAnim("move_ped_mop")
end)

RegisterNetEvent('SetCustomMovementStyle:chic')
AddEventHandler('SetCustomMovementStyle:chic', function()
	SetMovementAnim("MOVE_M@POSH@")
end)

RegisterNetEvent('SetCustomMovementStyle:dur')
AddEventHandler('SetCustomMovementStyle:dur', function()
	SetMovementAnim("MOVE_M@TOUGH_GUY@")
end)

RegisterNetEvent('SetCustomMovementStyle:chic')
AddEventHandler('SetCustomMovementStyle:chic', function()
	SetMovementAnim("MOVE_M@POSH@")
end)

RegisterNetEvent('SetCustomMovementStyle:lent')
AddEventHandler('SetCustomMovementStyle:lent', function()
	SetMovementAnim("move_p_m_zero_slow")
end)

RegisterNetEvent('SetCustomMovementStyle:accroupi')
AddEventHandler('SetCustomMovementStyle:accroupi', function()
	SetMovementAnim("move_ped_crouched")
end)

RegisterNetEvent('SetCustomMovementStyle:blesse')
AddEventHandler('SetCustomMovementStyle:blesse', function()
	SetMovementAnim("move_injured_generic")
end)

RegisterNetEvent('SetCustomMovementStyle:legerementbourre')
AddEventHandler('SetCustomMovementStyle:legerementbourre', function()
	SetMovementAnim("MOVE_M@DRUNK@SLIGHTLYDRUNK")
end)

RegisterNetEvent('SetCustomMovementStyle:bourre')
AddEventHandler('SetCustomMovementStyle:bourre', function()
	SetMovementAnim("MOVE_M@DRUNK@MODERATEDRUNK")
end)

RegisterNetEvent('SetCustomMovementStyle:tresbourre')
AddEventHandler('SetCustomMovementStyle:tresbourre', function()
	SetMovementAnim("MOVE_M@DRUNK@VERYDRUNK")
end)

RegisterNetEvent('SetCustomMovementStyle:feffraye')
AddEventHandler('SetCustomMovementStyle:feffraye', function()
	SetMovementAnim("move_f@scared")
end)

RegisterNetEvent('SetCustomMovementStyle:sexy')
AddEventHandler('SetCustomMovementStyle:sexy', function()
	SetMovementAnim("move_f@sexy@a")
end)

RegisterNetEvent('SetCustomMovementStyle:feminine')
AddEventHandler('SetCustomMovementStyle:feminine', function()
	SetMovementAnim("MOVE_F@FEMME@")
end)

function DrawNotif(text)
	SetNotificationTextEntry("STRING")
	AddTextComponentString(text)
	DrawNotification(false, false)
end

function PlayScenario1(param1) 
	Citizen.CreateThread(function()
		TaskStartScenarioInPlace(GetPlayerPed(-1), param1, 0, 1)
		Citizen.Wait(20000)
		ClearPedTasksImmediately(GetPlayerPed(-1))
	end)
end

function Toxicated()
          TaskStartScenarioInPlace(GetPlayerPed(-1), "WORLD_HUMAN_DRUG_DEALER", 0, 1)
          Citizen.Wait(2000)
          DoScreenFadeOut(500)
          Citizen.Wait(500)
          ClearPedTasksImmediately(GetPlayerPed(-1))
          SetTimecycleModifier("spectator5")
          SetPedMotionBlur(GetPlayerPed(-1), true)
          SetPedMovementClipset(GetPlayerPed(-1), "MOVE_M@DRUNK@SLIGHTLYDRUNK", true)
          SetPedIsDrunk(GetPlayerPed(-1), true)
          DoScreenFadeIn(500)
end

function reality()
          Citizen.Wait(300000)
          DoScreenFadeOut(1000)
          Citizen.Wait(1000)
          DoScreenFadeIn(1000)
          ClearTimecycleModifier()
          ResetScenarioTypesEnabled()
          ResetPedMovementClipset(GetPlayerPed(-1), 0)
          SetPedIsDrunk(GetPlayerPed(-1), false)
          SetPedMotionBlur(GetPlayerPed(-1), false)
          DrawNotif("~g~Retour à la réalité~s~")
end

RegisterNetEvent("cigarettes:fumer")
AddEventHandler("cigarettes:fumer", function()
local player = GetPlayerPed(-1)
local currentHealth = GetEntityHealth(player)
	   PlayScenario1("WORLD_HUMAN_SMOKING")                  
	   Wait(20000)
	   SetEntityHealth(player, currentHealth - 5)
       DrawNotif("Tu as fumé une ~g~cigarette")        
end)

RegisterNetEvent("petard:fumer")
AddEventHandler("petard:fumer", function()
local player = GetPlayerPed(-1)
local currentHealth = GetEntityHealth(player)
	   PlayScenario1("WORLD_HUMAN_SMOKING_POT") 
	   Wait(20000) 
	   SetEntityHealth(player, currentHealth - 5)
       DrawNotif("Tu as fumé un ~g~joint")
       Citizen.Wait(60000)
       DrawNotif("~r~Attention tu commence a etre défoncé~s~")
       Citizen.Wait(30000)
       DrawNotif("~r~Voila tu es défoncé~s~")
       Citizen.Wait(1000)
	   Toxicated()
	   Citizen.Wait(100)
	   reality()    
end)

function PlayScenario3(param1) 
	Citizen.CreateThread(function()
		TaskStartScenarioInPlace(GetPlayerPed(-1), param1, 0, 1)
		Citizen.Wait(20000)
		ClearPedTasksImmediately(GetPlayerPed(-1))
	end)
end

RegisterNetEvent("medecin:soins")
AddEventHandler("medecin:soins", function()
local player = GetPlayerPed(-1)
	   PlayScenario3("WORLD_HUMAN_YOGA")                       
	   Wait(20000)  
	   SetEntityHealth(player, 200)
       DrawNotif("Tu t'es ~g~soigné")   
end)

RegisterNetEvent('connecting')
AddEventHandler('connecting', function()
	TriggerServerEvent('connect')
end)